# Generated by Django 6.1 on 2026-09-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0042_alter_examination_question_paper_pdf_and_more'),
        ('games', '0002_weeklyquiz_weeklyquizattempt_weeklyquizanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='bot_difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_matches', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='is_bot_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='matchmaking_timeout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='bot_answer_delay',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='bot_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='bot_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='bot_selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
