# Generated by Django 6.1 on 2026-08-15 09:52

import django.db.models.deletion
import gamification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_referrals', models.IntegerField(unique=True)),
                ('xp_reward', models.IntegerField(default=0)),
                ('coins_reward', models.IntegerField(default=0)),
                ('badge_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('referrer_xp_reward', models.IntegerField(default=100)),
                ('referred_xp_reward', models.IntegerField(default=50)),
                ('referrer_coins_reward', models.IntegerField(default=50)),
                ('referred_coins_reward', models.IntegerField(default=25)),
                ('qualification_action', models.CharField(default='signup', max_length=50)),
                ('reward_processing', models.CharField(default='automatic', max_length=20)),
                ('xp_per_level', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'Referral Setting',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=gamification.models.generate_referral_code, max_length=20, unique=True)),
                ('xp', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('rewarded', 'Rewarded'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qualification_date', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
