# Generated by Django 6.1 on 2026-08-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('exams', '0017_alter_chapter_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='exams.exam'),
        ),
        migrations.DeleteModel(
            name='CourseModule',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
