# Generated by Django 6.1 on 2026-08-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_application_and_plan_course_link'),
        ('marketplace', '0002_product_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='marketplace_payment',
            field=models.ForeignKey(blank=True, help_text='If purchased via marketplace instead of subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_applications', to='marketplace.paymentsubmission'),
        ),
    ]
