# Generated by Django 6.1 on 2026-09-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('coming_soon', 'Coming Soon'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
