# Generated by Django 6.1 on 2026-08-21 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_application_and_plan_course_link'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The Course this plan grants enrollment access to. When payment is approved, student is enrolled in this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plans', to='courses.course'),
        ),
    ]
