# Generated by Django 6.1 on 2026-08-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_course_application_and_plan_course_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
