# Generated by Django 6.1 on 2026-09-02 12:52

import core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='screenshot',
            field=models.ImageField(upload_to='subscriptions/payment_proofs/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
