# Generated by Django 6.1 on 2026-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscriptionpayment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allowed_preparation_count',
            field=models.IntegerField(default=1, help_text='Number of preparations (courses) allowed for this plan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_flexible',
            field=models.BooleanField(default=False, help_text='If true, the student can pick up to `allowed_preparation_count` courses. If false, it uses the fixed `course` field.'),
        ),
    ]
