# Generated by Django 6.1 on 2026-09-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_thumbnail'),
        ('subscriptions', '0005_subscriptionplan_allowed_preparation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='eligible_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this package can grant access to. Used for MULTI and BUNDLE types.', related_name='eligible_plans', to='courses.course'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='package_type',
            field=models.CharField(choices=[('SINGLE', 'Single Preparation'), ('MULTI', 'Multi Preparation'), ('BUNDLE', 'Bundle'), ('ALL_ACCESS', 'All Access')], default='SINGLE', help_text='Type of package dictating the access rules.', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='allowed_preparation_count',
            field=models.IntegerField(default=1, help_text='Number of preparations allowed for this plan (used for MULTI packages)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Legacy/Single: The Course this plan grants enrollment access to. When payment is approved, student is enrolled in this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plans', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_flexible',
            field=models.BooleanField(default=False, help_text="Deprecated: Use package_type='MULTI'. If true, the student can pick up to `allowed_preparation_count` courses."),
        ),
    ]
