# Generated by Django 6.1 on 2026-09-09 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_coming_soon_status'),
        ('subscriptions', '0006_subscriptionplan_eligible_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_selections', to='courses.course')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='subscriptions.subscriptionpayment')),
            ],
            options={
                'ordering': ['selected_at'],
                'unique_together': {('payment', 'course')},
            },
        ),
    ]
