# Generated by Django 6.1 on 2026-09-23 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_canonical_course_hierarchy_data'),
        ('subscriptions', '0007_subscription_course_selection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptioncourseselection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscription',
            name='admin_grant_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='source',
            field=models.CharField(choices=[('CUSTOMER_PAYMENT', 'Customer Payment'), ('ADMIN_GRANT', 'Admin Grant')], default='CUSTOMER_PAYMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptioncourseselection',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='subscriptioncourseselection',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='subscriptions.subscriptionpayment'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncourseselection',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment', 'course'), name='unique_payment_course_selection'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncourseselection',
            constraint=models.UniqueConstraint(condition=models.Q(('subscription__isnull', False)), fields=('subscription', 'course'), name='unique_subscription_course_selection'),
        ),
    ]
