# Generated by Django 6.1 on 2026-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscriptionplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='ai_verification_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when AI verification was performed', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='verification_result',
            field=models.JSONField(blank=True, default=dict, help_text='Stores AI/OCR verification metadata: detected_amount, confidence_score, detected_transaction_id, error_message, etc.'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='verification_status',
            field=models.CharField(choices=[('NOT_VERIFIED', 'Not Verified'), ('VERIFICATION_IN_PROGRESS', 'Verification In Progress'), ('VERIFIED_CONFIDENT', 'Verified - Confident'), ('VERIFIED_UNCERTAIN', 'Verified - Uncertain (Awaiting Manual Review)'), ('VERIFICATION_FAILED', 'Verification Failed')], default='NOT_VERIFIED', help_text='Tracks AI/OCR verification progress and confidence level', max_length=30),
        ),
    ]
