# Generated by Django 6.1 on 2026-10-05 10:25

import core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionpayment_ai_verification_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='screenshot',
            field=models.ImageField(max_length=500, upload_to='subscriptions/payment_proofs/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
