# Generated by Django 6.1 on 2026-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscriptionpayment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='transaction_id',
            field=models.CharField(max_length=255),
        ),
    ]
