# Generated by Django 6.1 on 2026-08-14 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0015_questionset_set_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('exams', 'Exams & Tests'), ('question_bank', 'Question Bank'), ('ai_tutor', 'AI Tutor'), ('study_plan', 'Study Plan'), ('practice', 'Practice'), ('marketplace', 'Marketplace'), ('account', 'Account & Security'), ('payments', 'Payments'), ('technical', 'Technical Issues')], default='exams', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-helpful_count'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_reminders', models.BooleanField(default=True)),
                ('exam_starting_soon', models.BooleanField(default=True)),
                ('exam_deadline', models.BooleanField(default=True)),
                ('result_published', models.BooleanField(default=True)),
                ('study_plan_reminders', models.BooleanField(default=True)),
                ('practice_reminders', models.BooleanField(default=True)),
                ('daily_progress', models.BooleanField(default=True)),
                ('ai_tutor_updates', models.BooleanField(default=True)),
                ('study_recommendations', models.BooleanField(default=True)),
                ('order_updates', models.BooleanField(default=True)),
                ('marketplace_notifications', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('account_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('preferred_study_time', models.CharField(choices=[('morning', 'Morning (6AM - 12PM)'), ('afternoon', 'Afternoon (12PM - 5PM)'), ('evening', 'Evening (5PM - 9PM)'), ('night', 'Night (9PM - 12AM)'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('daily_study_goal_minutes', models.IntegerField(default=120)),
                ('difficulty_preference', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('study_mode', models.CharField(choices=[('practice', 'Practice'), ('revision', 'Revision'), ('mock_exams', 'Mock Exams'), ('balanced', 'Balanced')], default='balanced', max_length=20)),
                ('show_profile', models.BooleanField(default=False)),
                ('show_leaderboard', models.BooleanField(default=True)),
                ('allow_comparisons', models.BooleanField(default=False)),
                ('allow_activity_visibility', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_students', to='exams.examcategory')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_students', to='exams.exam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support/attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('exam_problem', 'Exam Problem'), ('wrong_question', 'Wrong Question/Answer'), ('technical', 'Technical Issue'), ('ai_tutor', 'AI Tutor Problem'), ('account', 'Account Problem'), ('payment', 'Payment/Marketplace'), ('other', 'Other')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_student', 'Waiting for Student'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('related_exam', models.CharField(blank=True, max_length=255)),
                ('related_question', models.CharField(blank=True, max_length=255)),
                ('related_page', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket'),
        ),
        migrations.CreateModel(
            name='FAQFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='support.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('faq', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['student', 'status'], name='support_sup_student_cea6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_number'], name='support_sup_ticket__4a7d4b_idx'),
        ),
    ]
