# Generated by Django 6.1 on 2026-09-02 12:52

import core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_studentprofile_focus_mode_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportattachment',
            name='file',
            field=models.FileField(upload_to='support/attachments/%Y/%m/', validators=[core.upload_validators.validate_document_size_20mb, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
