# Generated by Django 6.1 on 2026-09-05 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_studentprofile_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='access_origin',
            field=models.CharField(choices=[('SELF_REGISTERED', 'Self-Registered'), ('ADMIN_GRANTED', 'Admin-Granted')], default='SELF_REGISTERED', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admin_access_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admin_access_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admin_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admin_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
