# Generated by Django 6.1 on 2026-09-08 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_thumbnail'),
        ('support', '0006_studentprofile_access_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_students', to='courses.course'),
        ),
    ]
