# Generated by Django 6.1 on 2026-08-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_exam_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expected_time_minutes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.TextField(blank=True, help_text='Reference answer for evaluators'),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('subjective', 'Subjective')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
