# Generated by Django 6.1 on 2026-08-14 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_question_expected_time_minutes_question_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectiveanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question'),
        ),
        migrations.RemoveField(
            model_name='subjectivepracticeset',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='subjectivemodelexam',
            name='questions',
        ),
        migrations.AddField(
            model_name='subjectivepracticeset',
            name='questions',
            field=models.ManyToManyField(related_name='practice_sets', to='exams.question'),
        ),
        migrations.DeleteModel(
            name='SubjectiveQuestion',
        ),
        migrations.AddField(
            model_name='subjectivemodelexam',
            name='questions',
            field=models.ManyToManyField(related_name='subjective_model_exams', to='exams.question'),
        ),
    ]
