# Generated by Django 6.1 on 2026-08-14 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_subjectiveanswer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(blank=True, help_text='Permanent unique ID (e.g., Q-000001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of string tags'),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_questions', models.IntegerField()),
                ('difficulty_distribution', models.JSONField(default=dict, help_text="e.g., {'easy': 20, 'medium': 20, 'hard': 10}")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='exams.examcategory')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='exams.exam')),
                ('questions', models.ManyToManyField(related_name='question_sets', to='exams.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='exams.subject')),
            ],
        ),
    ]
