# Generated by Django 6.1 on 2026-08-14 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_question_question_id_question_tags_questionset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='ai_generate_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(blank=True, help_text='Permanent unique ID (e.g., Q-000001)', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='QuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Hex code or tailwind class', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, related_name='collections', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list, help_text='List of strings')),
                ('apply_to_new', models.BooleanField(default=True)),
                ('apply_to_csv', models.BooleanField(default=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='exams.questioncollection')),
            ],
        ),
        migrations.CreateModel(
            name='AIClassificationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='exams.question')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.questioncollection')),
            ],
        ),
    ]
