# Generated by Django 6.1 on 2026-08-14 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_remove_question_tags_question_ai_generate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionset',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='questions',
        ),
        migrations.AddField(
            model_name='questionset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='marks_per_question',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='questionset',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='negative_marking_value',
            field=models.FloatField(default=0.2, help_text='Amount deducted per wrong answer'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='passing_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='questionset',
            name='randomize_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Time limit in minutes'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='total_marks',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='exam',
            field=models.ForeignKey(help_text='Position / Level', on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='exams.exam'),
        ),
        migrations.CreateModel(
            name='QuestionSetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('marks', models.FloatField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set_questions', to='exams.questionset')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question_set', 'question')},
            },
        ),
    ]
