# Generated by Django 6.1 on 2026-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_rename_title_questionset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(related_name='question_sets', through='exams.QuestionSetQuestion', to='exams.question'),
        ),
    ]
