# Generated by Django 6.1 on 2026-08-14 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_questionset_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('mock', 'Mock Test'), ('practice', 'Practice Test'), ('full', 'Full-Length Exam'), ('position', 'Position-Based Exam'), ('subject', 'Subject Test'), ('custom', 'Custom Exam')], default='mock', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exams/thumbnails/')),
                ('total_questions', models.IntegerField(default=0)),
                ('time_limit', models.IntegerField(default=60, help_text='Time limit in minutes')),
                ('total_marks', models.FloatField(default=100)),
                ('passing_marks', models.FloatField(default=0)),
                ('marks_per_question', models.FloatField(default=1)),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_marking_value', models.FloatField(default=0.2)),
                ('max_attempts', models.IntegerField(default=1, help_text='0 for Unlimited')),
                ('allow_resume', models.BooleanField(default=True)),
                ('auto_submit', models.BooleanField(default=True)),
                ('result_visibility', models.CharField(choices=[('immediate', 'Immediately'), ('after_end', 'After Exam Ends'), ('manual', 'After Manual Review')], default='immediate', max_length=20)),
                ('show_correct_answers', models.BooleanField(default=False)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_options', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='exams.examcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(help_text='Position / Level', on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='exams.exam')),
                ('question_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='exams.questionset')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='exams.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in-progress', 'In Progress'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated')], default='in-progress', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='If True, all students can access')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='exams.examination')),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examcategory')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.FloatField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examinationattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
