# Generated by Django 6.1 on 2026-08-14 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examination_examinationattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='set_type',
            field=models.CharField(choices=[('full_mock', 'Full Mock Set'), ('subject', 'Subject Set'), ('chapter', 'Chapter Set'), ('topic', 'Topic Set'), ('position', 'Position-wise Set'), ('custom', 'Custom Set')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='questionset',
            name='subject_distribution',
            field=models.JSONField(blank=True, default=dict, help_text="For Full Mock sets, format: {'subject_id': count}"),
        ),
        migrations.AddField(
            model_name='questionset',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='exams.unit'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='exams.subject'),
        ),
    ]
