# Generated by Django 6.1 on 2026-08-16 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_questionset_reviewed_at_questionset_reviewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mock_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='reviewer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examination',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='examination',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='exams.subject'),
        ),
        migrations.CreateModel(
            name='ExaminationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('marks', models.FloatField(default=1)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_questions', to='exams.examination')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('examination', 'question')},
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='questions',
            field=models.ManyToManyField(related_name='examinations_set', through='exams.ExaminationQuestion', to='exams.question'),
        ),
    ]
