# Generated by Django 6.1 on 2026-08-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_examination_reviewed_at_examination_reviewed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyModelExamMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_migrations', to='exams.examination')),
                ('legacy_model_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='exams.modelexam')),
            ],
            options={
                'unique_together': {('legacy_model_exam', 'examination')},
            },
        ),
    ]
