# Generated by Django 6.1 on 2026-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_legacymodelexammigration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam',
        ),
        migrations.AlterField(
            model_name='examination',
            name='exam_type',
            field=models.CharField(choices=[('mock', 'Mock Test'), ('practice', 'Practice Test'), ('full', 'Full-Length Exam'), ('position', 'Position-Based Exam'), ('subject', 'Subject Test'), ('custom', 'Custom Exam'), ('subjective', 'Subjective Exam')], default='mock', max_length=20),
        ),
    ]
