# Generated by Django 6.1 on 2026-08-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_application_and_plan_course_link'),
        ('exams', '0023_remove_subject_exam_alter_examination_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Specific course this mock exam belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='courses.course'),
        ),
    ]
