# Generated by Django 6.1 on 2026-08-29 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_examination_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Loksewa Section Officer 2083 First Paper', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exam_date', models.DateField(help_text='Official Exam Date (YYYY-MM-DD)')),
                ('exam_time', models.TimeField(blank=True, help_text='Exam start time (e.g. 08:00:00 or 11:00:00)', null=True)),
                ('exam_datetime', models.DateTimeField(blank=True, help_text='Timezone-aware UTC datetime calculated from exam_date and exam_time', null=True)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('result_expected_date', models.DateField(blank=True, null=True)),
                ('official_notice_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='If True, this is considered the active Next Loksewa Exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, help_text='Specific Position / Level (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='exams.exam')),
                ('exam_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='exams.examcategory')),
            ],
            options={
                'ordering': ['-is_active', 'exam_date', 'exam_time', '-created_at'],
            },
        ),
    ]
