# Generated by Django 6.1 on 2026-08-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
