# Generated by Django 6.1 on 2026-08-30 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_questionattempt_is_viewed_questionattempt_viewed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('timed', 'Timed'), ('study', 'Study'), ('revision', 'Revision')], default='flexible', max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('consecutive_correct', models.IntegerField(default=0)),
                ('consecutive_incorrect', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('interval_days', models.IntegerField(default=1)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='exams.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
