# Generated by Django 6.1 on 2026-08-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_alter_practicesession_mode_questionmastery'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='objective_category',
            field=models.CharField(blank=True, choices=[('old_past', 'Old Past Exam'), ('model', 'Model Exam'), ('live', 'Live Exam'), ('custom', 'Create Your Own Exam')], max_length=20, null=True),
        ),
    ]
