# Generated by Django 6.1 on 2026-08-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_examination_objective_category'),
    ]

    operations = [
        # AlterUniqueTogether must run before the RemoveField operations below
        # drop the 'attempt'/'question' columns it indexes - the autodetector
        # ordered these backwards, which makes the schema editor look up a
        # column that's already gone from the model state.
        migrations.AlterUniqueTogether(
            name='modelexamattemptanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modelexam',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='modelexam',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='modelexamattempt',
            name='model_exam',
        ),
        migrations.RemoveField(
            model_name='modelexamattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='modelexamattemptanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='modelexamattemptanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='LegacyModelExamMigration',
        ),
        migrations.DeleteModel(
            name='ModelExam',
        ),
        migrations.DeleteModel(
            name='ModelExamAttempt',
        ),
        migrations.DeleteModel(
            name='ModelExamAttemptAnswer',
        ),
    ]
