# Generated by Django 6.1 on 2026-08-31 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_remove_modelexam_exam_remove_modelexam_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalmSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('audio_enabled', 'Audio Enabled')], max_length=20)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calm_session_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
