# Generated by Django 6.1 on 2026-08-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0030_calmsessionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('timed', 'Timed'), ('study', 'Study'), ('revision', 'Revision'), ('daily', 'Daily Practice')], default='flexible', max_length=20),
        ),
    ]
