# Generated by Django 6.1 on 2026-09-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0032_alter_examination_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exams.exam'),
        ),
    ]
