# Generated by Django 6.1 on 2026-09-03 09:51

from django.db import migrations

# The registration form's fixed top-level "What are you preparing for?"
# choices (see spec section 1) - seeded as real, admin-editable ExamCategory
# rows rather than hardcoded frontend strings, so an admin can rename them or
# add a 5th category later through the existing category CRUD with no
# frontend change. Deeper levels (PSC's Level/Service-Faculty) are NOT
# seeded here - those are for an admin to create under "PSC Exams" via the
# existing Exam CRUD, using the new self-referential Exam.parent field.
CATEGORIES = ['PSC Exams', 'Licence Exam', 'Entrance Exam', 'University Exam']

# A starting PSC Level -> Service/Faculty hierarchy, matching the spec's own
# worked example exactly, using the new Exam.parent field. Purely a seed -
# admins can rename, add, or remove levels/services afterward through the
# existing Exam CRUD; nothing here is hardcoded in the frontend.
PSC_LEVELS = {
    '4th Level': ['Civil'],
    '5th Level': ['Civil', 'Computer'],
    '7th Level': ['Civil', 'Computer', 'Surveyor'],
}



# Ordered well after the model's own default order=0, so these seeded rows
# never silently win a tie-break "which comes first" against categories
# other code (including existing tests) creates without specifying an
# order - order=0 is the ExamCategory.order field's own default, so it's
# effectively already spoken for.
SEED_ORDER_START = 100


def seed_categories(apps, schema_editor):
    ExamCategory = apps.get_model('exams', 'ExamCategory')
    Exam = apps.get_model('exams', 'Exam')
    for i, name in enumerate(CATEGORIES):
        ExamCategory.objects.get_or_create(name=name, defaults={'order': SEED_ORDER_START + i, 'is_active': True})

    psc, _ = ExamCategory.objects.get_or_create(name='PSC Exams', defaults={'order': SEED_ORDER_START, 'is_active': True})
    for level_order, (level_name, services) in enumerate(PSC_LEVELS.items()):
        level, _ = Exam.objects.get_or_create(
            category=psc, name=level_name, parent=None, defaults={'order': level_order, 'is_active': True}
        )
        for service_order, service_name in enumerate(services):
            Exam.objects.get_or_create(
                category=psc, name=service_name, parent=level,
                defaults={'order': service_order, 'is_active': True},
            )


def remove_categories(apps, schema_editor):
    ExamCategory = apps.get_model('exams', 'ExamCategory')
    Exam = apps.get_model('exams', 'Exam')
    psc = ExamCategory.objects.filter(name='PSC Exams').first()
    if psc:
        Exam.objects.filter(category=psc, name__in=PSC_LEVELS.keys()).delete()
    ExamCategory.objects.filter(name__in=CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0033_exam_parent'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
