# Generated by Django 6.1 on 2026-09-09 16:30

from django.db import migrations, models


def backfill_status_from_is_active(apps, schema_editor):
    """Preserve existing state: a row already marked is_active=False becomes
    status='inactive' instead of silently reactivating as the new field's
    default('active')."""
    Exam = apps.get_model('exams', 'Exam')
    Exam.objects.filter(is_active=False).update(status='inactive')


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0034_seed_registration_exam_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.RunPython(backfill_status_from_is_active, migrations.RunPython.noop),
    ]
