# Generated by Django 6.1 on 2026-09-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_adminsettings_max_login_attempts'),
        ('exams', '0035_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag_objects',
            field=models.ManyToManyField(blank=True, help_text='Structured tags for search, filtering and discovery.', related_name='questions', to='core.tag'),
        ),
    ]
