# Generated by Django 6.1 on 2026-09-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0036_question_tag_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='Optional hint shown to help the student answer'),
        ),
    ]
