# Generated by Django 6.1 on 2026-09-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0037_question_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
