# Generated by Django 6.1 on 2026-09-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0038_studentanswer_evaluated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmastery',
            name='last_due_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
