# Generated by Django 6.1 on 2026-09-24 05:05

import core.upload_validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0039_questionmastery_last_due_review_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='allowed_file_types',
            field=models.CharField(default='jpg,jpeg,png,webp,pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='examination',
            name='answer_upload_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='evaluation_type',
            field=models.CharField(choices=[('admin', 'Admin Evaluation'), ('ai', 'AI Evaluation'), ('hybrid', 'Hybrid Evaluation')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='examination',
            name='max_upload_size_mb',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='examination',
            name='question_paper_file_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='question_paper_page_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='question_paper_pdf',
            field=models.FileField(blank=True, null=True, upload_to='subjective_exams/question_papers/', validators=[core.upload_validators.validate_document_size_20mb, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='examination',
            name='upload_deadline_minutes',
            field=models.IntegerField(default=30, help_text='Minutes allowed to upload answer sheets after exam duration expires'),
        ),
        migrations.AddField(
            model_name='examination',
            name='upload_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='upload_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examinationattempt',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('upload_pending', 'Upload Pending'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated')], default='in-progress', max_length=20),
        ),
        migrations.CreateModel(
            name='SubjectiveSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upload_pending', 'Upload Pending'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('processing_failed', 'Processing Failed'), ('evaluated', 'Evaluated')], default='upload_pending', max_length=25)),
                ('answer_pdf', models.FileField(blank=True, null=True, upload_to='subjective_exams/submissions/%Y/%m/')),
                ('page_count', models.IntegerField(default=0)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('raw_ocr_text', models.TextField(blank=True, help_text='Raw unedited handwriting extraction from OCR')),
                ('extracted_text', models.TextField(blank=True, help_text='Admin-verified / edited transcription')),
                ('ocr_status', models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('ocr_error', models.TextField(blank=True)),
                ('evaluator_feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_submission', to='exams.examinationattempt')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_subjective_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectiveQuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=1)),
                ('marks_obtained', models.FloatField(default=0)),
                ('max_marks', models.FloatField(default=10)),
                ('feedback', models.TextField(blank=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='exams.subjectivesubmission')),
            ],
            options={
                'ordering': ['question_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectiveSubmissionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
                ('image_file', models.FileField(upload_to='subjective_exams/pages/%Y/%m/')),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='exams.subjectivesubmission')),
            ],
            options={
                'ordering': ['page_number', 'id'],
                'unique_together': {('submission', 'page_number')},
            },
        ),
    ]
