# Generated by Django 6.1 on 2026-09-24 10:12

import django.db.models.deletion
from django.db import migrations, models


def populate_academic_parents(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    for q in Question.objects.filter(topic__isnull=False).select_related('topic__chapter__subject'):
        try:
            if q.topic and q.topic.chapter:
                q.chapter_id = q.topic.chapter_id
                q.subject_id = q.topic.chapter.subject_id
                q.save(update_fields=['chapter', 'subject'])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0040_examination_allowed_file_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.topic'),
        ),
        migrations.RunPython(populate_academic_parents, migrations.RunPython.noop),
    ]
