# Generated by Django 6.1 on 2026-09-24 12:37

import core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0041_question_optional_chapter_topic_add_subject_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='question_paper_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='subjective_exams/question_papers/', validators=[core.upload_validators.validate_document_size_20mb, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='examination',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='exams/thumbnails/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='subjectivesubmission',
            name='answer_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='subjective_exams/submissions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='subjectivesubmissionpage',
            name='image_file',
            field=models.FileField(max_length=500, upload_to='subjective_exams/pages/%Y/%m/'),
        ),
    ]
