# Generated by Django 6.1 on 2026-10-04 17:51

import django.db.models.deletion
import exams.issue_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0052_question_category_question_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('WRONG_QUESTION', 'Wrong Question'), ('WRONG_ANSWER', 'Wrong Answer'), ('WRONG_EXPLANATION', 'Wrong Explanation'), ('TYPO', 'Typo / Spelling Mistake'), ('AMBIGUOUS', 'Confusing / Ambiguous'), ('DUPLICATE', 'Duplicate Question'), ('WRONG_SUBJECT_TOPIC', 'Wrong Subject / Topic'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(max_length=2000)),
                ('suggested_correction', models.TextField(blank=True, max_length=1000)),
                ('evidence_file', models.FileField(blank=True, max_length=500, null=True, upload_to='question_reports/evidence/%Y/%m/', validators=[exams.issue_models.validate_evidence_file])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('NEEDS_INFORMATION', 'Needs Information')], db_index=True, default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_issue_reports', to='exams.examination')),
                ('examination_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_issue_reports', to='exams.examinationattempt')),
                ('practice_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_issue_reports', to='exams.practicesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='exams.question')),
                ('question_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_issue_reports', to='exams.questionattempt')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_question_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question', 'status'], name='exams_quest_questio_c4ed1d_idx'), models.Index(fields=['student', 'status'], name='exams_quest_student_a7c22f_idx'), models.Index(fields=['status', 'created_at'], name='exams_quest_status_1bf09e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'UNDER_REVIEW', 'NEEDS_INFORMATION'])), fields=('student', 'question', 'issue_type'), name='unique_active_student_question_issue')],
            },
        ),
    ]
