# Generated by Django 6.1 on 2026-10-08 09:40

import core.upload_validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0053_add_question_issue_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='expert_solution_file_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='expert_solution_page_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='expert_solution_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='subjective_exams/expert_solutions/%Y/%m/', validators=[core.upload_validators.validate_document_size_20mb, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp']), core.upload_validators.validate_pdf_upload]),
        ),
        migrations.AddField(
            model_name='examination',
            name='expert_solution_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='is_expert_solution_published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubjectiveCheckingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Checking Request Pending'), ('accepted', 'Checking Accepted'), ('in_progress', 'Checking in Progress'), ('completed', 'Checking Completed'), ('rejected', 'Request Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checking_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checking_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_checking_requests', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checking_requests', to='exams.subjectivesubmission')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission', 'status'], name='exams_subje_submiss_79c11c_idx'), models.Index(fields=['student', 'status'], name='exams_subje_student_f721f0_idx')],
            },
        ),
    ]
