# Generated by Django 6.1 on 2026-10-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0054_examination_expert_solution_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='auto_publish_eligible',
            field=models.BooleanField(default=False, help_text='Auto-publish results when AI quality gate passes'),
        ),
        migrations.AddField(
            model_name='examination',
            name='expert_solution_extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from Expert Solution PDF'),
        ),
        migrations.AddField(
            model_name='examination',
            name='expert_solution_rubric_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examination',
            name='expert_solution_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='evaluation_type',
            field=models.CharField(choices=[('descriptive', 'Descriptive'), ('numerical', 'Numerical/Derivation'), ('diagram', 'Diagram-based'), ('mcq', 'Objective MCQ')], default='descriptive', max_length=30),
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='model_solution',
            field=models.TextField(blank=True, help_text='Solution extracted for this question'),
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='question_number',
            field=models.CharField(blank=True, help_text='Canonical label, e.g. Q1, Q2, 1(a)', max_length=20),
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='rubric',
            field=models.JSONField(blank=True, default=list, help_text='Structured marking rubric criteria'),
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='rubric_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='rubric_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal evaluator notes'),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='criterion_scores',
            field=models.JSONField(blank=True, default=list, help_text='Criterion-wise partial scores'),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='improvements',
            field=models.TextField(blank=True, help_text='Suggested improvements'),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='pages_referred',
            field=models.JSONField(blank=True, default=list, help_text='Source page numbers'),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='rubric_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Approved rubric criteria snapshot'),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ai_evaluated', 'AI Evaluated'), ('needs_review', 'Needs Review'), ('admin_confirmed', 'Admin Confirmed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='strengths',
            field=models.TextField(blank=True, help_text='What student did well'),
        ),
        migrations.AddField(
            model_name='subjectivequestionscore',
            name='student_answer_text',
            field=models.TextField(blank=True, help_text='Extracted student answer text'),
        ),
        migrations.AddField(
            model_name='subjectivesubmission',
            name='audit_trail',
            field=models.JSONField(blank=True, default=list, help_text='Audit log of score changes'),
        ),
        migrations.AddField(
            model_name='subjectivesubmission',
            name='evaluation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ocr_processing', 'OCR Processing'), ('ai_evaluating', 'AI Evaluating'), ('ai_evaluated', 'AI Evaluated'), ('needs_review', 'Needs Review'), ('admin_confirmed', 'Admin Confirmed'), ('published', 'Published')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='subjectivesubmission',
            name='quality_gate_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subjectivesubmission',
            name='quality_gate_passed',
            field=models.BooleanField(default=False),
        ),
    ]
