# Generated by Django 6.1 on 2026-08-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_examination_reviewed_at_examination_reviewed_by_and_more'),
        ('study_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_templates', to='exams.exam')),
            ],
        ),
        migrations.AddField(
            model_name='studyplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='study_plan.studyplantemplate'),
        ),
        migrations.CreateModel(
            name='StudyPlanTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day 1, Day 2, etc.')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('STUDY_NOTE', 'Study Note'), ('PRACTICE', 'Practice'), ('MODEL_EXAM', 'Model Exam'), ('SUBJECTIVE_PRACTICE', 'Subjective Practice'), ('REVIEW_MISTAKES', 'Review Mistakes'), ('REVISION', 'Revision')], max_length=50)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_plan.studyplantemplate')),
            ],
        ),
    ]
