# Generated by Django 6.1 on 2026-08-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseapplication_marketplace_payment'),
        ('exams', '0024_examination_course'),
        ('study_plan', '0002_studyplantemplate_studyplan_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplantemplate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan_templates', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studyplantemplatetask',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_tasks', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='studyplantemplatetask',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_tasks', to='exams.topic'),
        ),
        migrations.AlterField(
            model_name='studyplantemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
