# Generated by Django 6.1 on 2026-09-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0003_studyplantemplate_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='daily_questions',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
