# Generated by Django 6.1 on 2026-08-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0004_subjectiveanswer_evaluation_annotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description for the list view')),
                ('content', models.TextField(blank=True, help_text='Rich text content (HTML/Markdown)')),
                ('material_type', models.CharField(choices=[('notes', 'Notes'), ('pdf', 'PDF'), ('study_guide', 'Study Guide'), ('reference', 'Reference Material')], default='notes', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='study_materials/pdfs/')),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('estimated_reading_time', models.IntegerField(default=10, help_text='Estimated time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='exams.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='exams.topic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('completed', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='notes.studymaterial')),
            ],
            options={
                'ordering': ['-last_viewed_at'],
                'unique_together': {('student', 'material')},
            },
        ),
        migrations.CreateModel(
            name='StudentMaterialBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='notes.studymaterial')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'material')},
            },
        ),
    ]
