# Generated by Django 6.1 on 2026-08-20 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='external_url',
            field=models.URLField(blank=True, help_text='For videos or external resources', null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='review_note',
            field=models.TextField(blank=True, help_text='Admin feedback when changes are requested or rejected'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('pdf', 'PDF'), ('video', 'Video'), ('document', 'Document'), ('presentation', 'Presentation'), ('external_link', 'External Link'), ('study_guide', 'Study Guide'), ('reference', 'Reference Material')], default='notes', max_length=20),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('changes_requested', 'Changes Requested'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
