# Generated by Django 6.1 on 2026-08-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_application_and_plan_course_link'),
        ('notes', '0002_studymaterial_difficulty_studymaterial_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='courses.course'),
        ),
    ]
