# Generated by Django 6.1 on 2026-08-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_materialcategory_studymaterial_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='available_to_ai_tutor',
            field=models.BooleanField(default=False, help_text="When true and status=published, the AI Tutor may retrieve and quote this material's content as reference context for student questions."),
        ),
    ]
