# Generated by Django 6.1 on 2026-09-02 12:52

import core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_studymaterial_available_to_ai_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/pdfs/', validators=[core.upload_validators.validate_document_size_20mb, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
