# Generated by Django 6.1 on 2026-09-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0034_seed_registration_exam_categories'),
        ('notes', '0006_alter_studymaterial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='exams.chapter'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='content_category',
            field=models.CharField(choices=[('syllabus', 'Syllabus'), ('subjective_topicwise', 'Subjective Topicwise Notes [Detailed]'), ('objective_topicwise', 'Objective Topicwise Notes [Detailed]'), ('revision_notes', 'Revision Notes')], db_index=True, default='subjective_topicwise', max_length=50),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='note_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('ai', 'AI'), ('subjective', 'Subjective'), ('objective', 'Objective')], db_index=True, default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='exams.subject'),
        ),
    ]
