# Generated by Django 6.1 on 2026-09-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_studymaterial_chapter_studymaterial_content_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='order',
            field=models.IntegerField(db_index=True, default=0, help_text="Admin-controlled display order within its exam node (lower shows first) - used by the Syllabus Builder's material list and the public syllabus page."),
        ),
    ]
