# Generated by Django 6.1 on 2026-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_studymaterial_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='is_downloadable',
            field=models.BooleanField(default=True, help_text='When true, students are allowed to download the PDF file of this material.'),
        ),
    ]
