# Generated by Django 6.1 on 2026-08-26 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Loksewa', max_length=255)),
                ('platform_logo_url', models.URLField(blank=True, null=True)),
                ('platform_description', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('email_smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('email_smtp_port', models.IntegerField(blank=True, default=587, null=True)),
                ('email_smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('email_from_address', models.EmailField(blank=True, default='', max_length=254)),
                ('email_from_name', models.CharField(blank=True, default='', max_length=255)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_in_app_notifications', models.BooleanField(default=True)),
                ('enable_push_notifications', models.BooleanField(default=False)),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_special_chars', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('enable_two_factor_auth', models.BooleanField(default=False)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('enable_ai_tutor', models.BooleanField(default=True)),
                ('enable_marketplace', models.BooleanField(default=True)),
                ('enable_gamification', models.BooleanField(default=True)),
                ('enable_study_plans', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Admin Settings',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_positi_is_acti_322126_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('alert', 'Alert'), ('announcement', 'Announcement'), ('system', 'System')], default='announcement', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('target_role', models.CharField(default='all', help_text="Target audience: 'all', 'students', 'teachers', 'admins'", max_length=50)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_adminn_status_66431e_idx'), models.Index(fields=['type', '-created_at'], name='core_adminn_type_5045a7_idx')],
            },
        ),
    ]
