# Generated by Django 6.1 on 2026-08-27 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source_admin_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.adminnotification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('question_review', 'Question Review'), ('material_review', 'Study Material Review'), ('student_activity', 'Student Activity'), ('system', 'System Alert'), ('support', 'Support Response'), ('payment', 'Payment Notification'), ('announcement', 'Announcement'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
