# Generated by Django 6.1 on 2026-08-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_source_admin_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='ai_tutor_daily_message_limit',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
