# Generated by Django 6.1 on 2026-08-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_type_studentfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='audit_log_retention_days',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
