# Generated by Django 6.1 on 2026-08-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_is_2fa_enabled_user_totp_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('question_review', 'Question Review'), ('material_review', 'Study Material Review'), ('student_activity', 'Student Activity'), ('system', 'System Alert'), ('support', 'Support Response'), ('payment', 'Payment Notification'), ('announcement', 'Announcement'), ('feedback', 'Performance Feedback'), ('evaluation', 'Evaluation Queue'), ('course_application', 'Course Application'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
