# Generated by Django 6.1 on 2026-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('question_review', 'Question Review'), ('material_review', 'Study Material Review'), ('student_activity', 'Student Activity'), ('system', 'System Alert'), ('support', 'Support Response'), ('payment', 'Payment Notification'), ('announcement', 'Announcement'), ('feedback', 'Performance Feedback'), ('evaluation', 'Evaluation Queue'), ('course_application', 'Course Application'), ('new_registration', 'New Student Registration'), ('account', 'Account Update'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
