# Generated by Django 6.1 on 2026-09-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('question_review', 'Question Review'), ('material_review', 'Study Material Review'), ('student_activity', 'Student Activity'), ('system', 'System Alert'), ('support', 'Support Response'), ('payment', 'Payment Notification'), ('announcement', 'Announcement'), ('feedback', 'Performance Feedback'), ('evaluation', 'Evaluation Queue'), ('course_application', 'Course Application'), ('new_registration', 'New Student Registration'), ('account', 'Account Update'), ('exam', 'Exam'), ('result', 'Exam Result'), ('practice', 'Practice'), ('course', 'Course'), ('study_plan', 'Study Plan'), ('gamification', 'Gamification'), ('order', 'Order Update'), ('marketplace', 'Marketplace Activity'), ('community', 'Community Activity'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
