# Generated by Django 6.1 on 2026-09-03 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otps_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup Verification'), ('password_reset', 'Password Reset'), ('admin_recovery', 'Admin-Assisted Recovery')], max_length=20),
        ),
    ]
