# Generated by Django 6.1 on 2026-09-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_seed_website_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='enforce_subscription_access',
            field=models.BooleanField(default=False),
        ),
    ]
