# Generated by Django 6.1 on 2026-09-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_adminsettings_enforce_subscription_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='max_login_attempts',
            field=models.IntegerField(default=6),
        ),
    ]
