# Generated by Django 6.1 on 2026-08-22 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_application_and_plan_course_link'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.ForeignKey(blank=True, help_text='If this product is a course, link it here for automatic enrollment upon purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_products', to='courses.course'),
        ),
    ]
