# Generated by Django 6.1 on 2026-09-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_deliveryfeerule_orderstatushistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='course',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_file',
        ),
    ]
