# Generated by Django 6.1 on 2026-09-01 12:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_product_course_remove_product_is_free_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Platform fee deducted from seller earnings (%). 0 = no fee.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_listing_images', models.PositiveIntegerField(default=6, help_text='Maximum number of images a seller can upload per listing.')),
                ('allow_student_listings', models.BooleanField(default=True, help_text='When off, students cannot create new listings (existing ones unaffected).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace Settings',
                'verbose_name_plural': 'Marketplace Settings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='condition_details',
            field=models.JSONField(blank=True, default=dict, help_text='Structured physical condition info. Keys: highlighting (bool), writing_notes (bool), page_damage (bool), cover_condition (str), missing_pages (bool), water_damage (bool), binding_condition (str), extra_notes (str)'),
        ),
        migrations.AddField(
            model_name='product',
            name='publication_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin-written reason shown to the seller when a listing is rejected.'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='label',
            field=models.CharField(blank=True, choices=[('front_cover', 'Front Cover'), ('back_cover', 'Back Cover'), ('spine', 'Spine'), ('inside_pages', 'Inside Pages'), ('damage', 'Visible Damage'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('ACCEPTABLE', 'Acceptable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='listing_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SOLD', 'Sold'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='PENDING_REVIEW', max_length=20),
        ),
        migrations.CreateModel(
            name='MarketplaceListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_book', 'Fake or Incorrect Book'), ('wrong_condition', 'Condition Does Not Match Description'), ('misleading_images', 'Misleading Images'), ('wrong_price', 'Wrong or Manipulated Price'), ('spam', 'Spam or Duplicate Listing'), ('prohibited', 'Prohibited Item'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.product')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'reporter')},
            },
        ),
    ]
