# Generated by Django 6.1 on 2026-09-02 12:52

import core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_marketplacesettings_minimum_payout_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeevidence',
            name='image',
            field=models.ImageField(upload_to='marketplace/dispute_evidence/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/payment_qrs/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='screenshot',
            field=models.ImageField(upload_to='marketplace/payment_proofs/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/covers/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='marketplace/product_images/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
