# Generated by Django 6.1 on 2026-09-14 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='max_used_book_price_percent',
            field=models.DecimalField(decimal_places=2, default=65.0, help_text="A student-listed used book's asking price (Product.price) cannot exceed this percentage of its marked/printed price (Product.marked_price). Enforced in SellerListingSerializer.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='marked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
