# Generated by Django 6.1 on 2026-10-04 06:21

import core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_marketplacesettings_max_used_book_price_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='qr_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='marketplace/payment_qrs/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='screenshot',
            field=models.ImageField(max_length=500, upload_to='marketplace/payment_proofs/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='marketplace/covers/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='marketplace/product_images/', validators=[core.upload_validators.validate_image_size_5mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
