# Generated by Django 6.1 on 2026-08-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auditlog_details_alter_auditlog_entity_id_csvimport'),
        ('exams', '0024_examination_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='difficulty',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='question_type',
            field=models.CharField(default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to='exams.topic'),
        ),
    ]
