# Generated by Django 6.1 on 2026-09-13 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_exportjob'),
        ('core', '0028_alter_adminsettings_max_login_attempts'),
        ('exams', '0037_question_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to='exams.questioncollection'),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='tag_objects',
            field=models.ManyToManyField(blank=True, related_name='csv_imports', to='core.tag'),
        ),
    ]
