# Generated by Django 6.1 on 2026-09-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_csvimport_collection_csvimport_tag_objects'),
        ('exams', '0042_alter_examination_question_paper_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to='exams.chapter'),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to='exams.subject'),
        ),
    ]
